<?php

/**
 * This is the model base class for the table "appform_nationality".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Nationality".
 *
 * Columns in table "appform_nationality" available as properties of the model,
 * followed by relations of table "appform_nationality" available as properties of the model.
 *
 * @property integer $id
 * @property string $nationality_description
 *
 * @property RepOffice[] $repOffices
 */
abstract class BaseNationality extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'appform_nationality';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Nationality|Nationalities', $n);
	}

	public static function representingColumn() {
		return 'nationality_description';
	}

	public function rules() {
		return array(
			array('nationality_description', 'required'),
			array('nationality_description', 'length', 'max'=>45),
			array('id, nationality_description', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'repOffices' => array(self::HAS_MANY, 'RepOffice', 'nationality_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'nationality_description' => Yii::t('app', 'Nationality Description'),
			'repOffices' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('nationality_description', $this->nationality_description, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}