<?php

/**
 * This is the model base class for the table "appform_general_project_site_history".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "GeneralProjectSiteHistory".
 *
 * Columns in table "appform_general_project_site_history" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $general_application_form_id
 * @property integer $province_id
 * @property integer $district_id
 * @property integer $village_id
 * @property integer $user_action_id
 * @property string $action_time
 *
 */
abstract class BaseGeneralProjectSiteHistory extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'appform_general_project_site_history';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'GeneralProjectSiteHistory|GeneralProjectSiteHistories', $n);
	}

	public static function representingColumn() {
		return 'action_time';
	}

	public function rules() {
		return array(
			array('id, general_application_form_id, province_id, district_id, user_action_id, action_time', 'required'),
			array('id, general_application_form_id, province_id, district_id, village_id, user_action_id', 'numerical', 'integerOnly'=>true),
			array('village_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, general_application_form_id, province_id, district_id, village_id, user_action_id, action_time', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'general_application_form_id' => Yii::t('app', 'General Application Form'),
			'province_id' => Yii::t('app', 'Province'),
			'district_id' => Yii::t('app', 'District'),
			'village_id' => Yii::t('app', 'Village'),
			'user_action_id' => Yii::t('app', 'User Action'),
			'action_time' => Yii::t('app', 'Action Time'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('general_application_form_id', $this->general_application_form_id);
		$criteria->compare('province_id', $this->province_id);
		$criteria->compare('district_id', $this->district_id);
		$criteria->compare('village_id', $this->village_id);
		$criteria->compare('user_action_id', $this->user_action_id);
		$criteria->compare('action_time', $this->action_time, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}