<?php

/**
 * This is the model base class for the table "appform_investor_region".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "InvestorRegion".
 *
 * Columns in table "appform_investor_region" available as properties of the model,
 * followed by relations of table "appform_investor_region" available as properties of the model.
 *
 * @property integer $id
 * @property string $region_name
 *
 * @property ApplicationForm[] $applicationForms
 */
abstract class BaseInvestorRegion extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'appform_investor_region';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'InvestorRegion|InvestorRegions', $n);
	}

	public static function representingColumn() {
		return 'region_name';
	}

	public function rules() {
		return array(
			array('region_name', 'required'),
			array('region_name', 'length', 'max'=>60),
			array('id, region_name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'applicationForms' => array(self::HAS_MANY, 'ApplicationForm', 'investor_region_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'region_name' => Yii::t('app', 'Region Name'),
			'applicationForms' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('region_name', $this->region_name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}