<?php

/**
 * This is the model base class for the table "appform_business_sector".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "BusinessSector".
 *
 * Columns in table "appform_business_sector" available as properties of the model,
 * followed by relations of table "appform_business_sector" available as properties of the model.
 *
 * @property integer $id
 * @property string $sector_name
 *
 * @property InvestCompany[] $investCompanies
 */
abstract class BaseBusinessSector extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'appform_business_sector';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'BusinessSector|BusinessSectors', $n);
	}

	public static function representingColumn() {
		return 'sector_name';
	}

	public function rules() {
		return array(
			array('sector_name', 'required'),
			array('sector_name', 'length', 'max'=>255),
			array('id, sector_name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'investCompanies' => array(self::HAS_MANY, 'InvestCompany', 'business_sector_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'sector_name' => Yii::t('app', 'Sector Name'),
			'investCompanies' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('sector_name', $this->sector_name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}