<?php

/**
 * This is the model base class for the table "appform_invest_company_history".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "InvestCompanyHistory".
 *
 * Columns in table "appform_invest_company_history" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $application_form_id
 * @property string $company_name
 * @property string $register_place
 * @property string $register_date
 * @property integer $total_capital
 * @property integer $capital
 * @property string $president_first_name
 * @property string $president_last_name
 * @property string $president_nationality
 * @property string $president_position
 * @property string $headquarter_address
 * @property integer $business_sector_id
 * @property integer $user_action_id
 * @property string $action_time
 *
 */
abstract class BaseInvestCompanyHistory extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'appform_invest_company_history';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'InvestCompanyHistory|InvestCompanyHistories', $n);
	}

	public static function representingColumn() {
		return 'company_name';
	}

	public function rules() {
		return array(
			array('id, application_form_id, company_name, register_place, register_date, total_capital, capital, president_first_name, president_last_name, president_nationality, president_position, headquarter_address, business_sector_id, user_action_id, action_time', 'required'),
			array('id, application_form_id, total_capital, capital, business_sector_id, user_action_id', 'numerical', 'integerOnly'=>true),
			array('company_name, register_place, president_first_name, president_last_name, president_nationality, president_position, headquarter_address', 'length', 'max'=>255),
			array('id, application_form_id, company_name, register_place, register_date, total_capital, capital, president_first_name, president_last_name, president_nationality, president_position, headquarter_address, business_sector_id, user_action_id, action_time', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'application_form_id' => Yii::t('app', 'Application Form'),
			'company_name' => Yii::t('app', 'Company Name'),
			'register_place' => Yii::t('app', 'Register Place'),
			'register_date' => Yii::t('app', 'Register Date'),
			'total_capital' => Yii::t('app', 'Total Capital'),
			'capital' => Yii::t('app', 'Capital'),
			'president_first_name' => Yii::t('app', 'President First Name'),
			'president_last_name' => Yii::t('app', 'President Last Name'),
			'president_nationality' => Yii::t('app', 'President Nationality'),
			'president_position' => Yii::t('app', 'President Position'),
			'headquarter_address' => Yii::t('app', 'Headquarter Address'),
			'business_sector_id' => Yii::t('app', 'Business Sector'),
			'user_action_id' => Yii::t('app', 'User Action'),
			'action_time' => Yii::t('app', 'Action Time'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('application_form_id', $this->application_form_id);
		$criteria->compare('company_name', $this->company_name, true);
		$criteria->compare('register_place', $this->register_place, true);
		$criteria->compare('register_date', $this->register_date, true);
		$criteria->compare('total_capital', $this->total_capital);
		$criteria->compare('capital', $this->capital);
		$criteria->compare('president_first_name', $this->president_first_name, true);
		$criteria->compare('president_last_name', $this->president_last_name, true);
		$criteria->compare('president_nationality', $this->president_nationality, true);
		$criteria->compare('president_position', $this->president_position, true);
		$criteria->compare('headquarter_address', $this->headquarter_address, true);
		$criteria->compare('business_sector_id', $this->business_sector_id);
		$criteria->compare('user_action_id', $this->user_action_id);
		$criteria->compare('action_time', $this->action_time, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}