<?php

/**
 * This is the model base class for the table "appform_mining_history".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MiningHistory".
 *
 * Columns in table "appform_mining_history" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $application_form_id
 * @property string $company_name
 * @property string $objective
 * @property integer $total_capital
 * @property integer $capital
 * @property integer $fixed_asset
 * @property integer $current_asset
 * @property integer $user_action_id
 * @property string $action_time
 *
 */
abstract class BaseMiningHistory extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'appform_mining_history';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MiningHistory|MiningHistories', $n);
	}

	public static function representingColumn() {
		return 'company_name';
	}

	public function rules() {
		return array(
			array('application_form_id, company_name, objective, total_capital, capital, fixed_asset, current_asset, user_action_id, action_time', 'required'),
			array('application_form_id, total_capital, province_id, district_id, village_id, capital, fixed_asset, current_asset, user_action_id', 'numerical', 'integerOnly'=>true),
			array('company_name, objective, address', 'length', 'max'=>255),
			array('application_form_id, company_name, objective, total_capital, capital, fixed_asset, current_asset, user_action_id, action_time', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'application_form_id' => Yii::t('app', 'Application Form'),
			'company_name' => Yii::t('app', 'Company Name'),
			'objective' => Yii::t('app', 'Objective'),
			'total_capital' => Yii::t('app', 'Total Capital'),
			'capital' => Yii::t('app', 'Capital'),
			'fixed_asset' => Yii::t('app', 'Fixed Asset'),
			'current_asset' => Yii::t('app', 'Current Asset'),
			'user_action_id' => Yii::t('app', 'User Action'),
			'action_time' => Yii::t('app', 'Action Time'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('application_form_id', $this->application_form_id);
		$criteria->compare('company_name', $this->company_name, true);
		$criteria->compare('objective', $this->objective, true);
		$criteria->compare('total_capital', $this->total_capital);
		$criteria->compare('capital', $this->capital);
		$criteria->compare('fixed_asset', $this->fixed_asset);
		$criteria->compare('current_asset', $this->current_asset);
		$criteria->compare('user_action_id', $this->user_action_id);
		$criteria->compare('action_time', $this->action_time, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}