<?php

/**
 * This is the model base class for the table "appform_electric_history".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ElectricHistory".
 *
 * Columns in table "appform_electric_history" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $application_form_id
 * @property string $project_name
 * @property string $company_name
 * @property string $mou
 * @property string $develop_contract
 * @property string $consession_contract
 * @property integer $user_action_id
 * @property string $action_time
 *
 */
abstract class BaseElectricHistory extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'appform_electric_history';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ElectricHistory|ElectricHistories', $n);
	}

	public static function representingColumn() {
		return 'project_name';
	}

	public function rules() {
		return array(
			array('application_form_id, project_name, company_name, user_action_id, action_time', 'required'),
			array('application_form_id, user_action_id, province_id, district_id, village_id,', 'numerical', 'integerOnly'=>true),
			array('project_name, company_name', 'length', 'max'=>255),
			array('mou, develop_contract, consession_contract', 'length', 'max'=>1),
			array('mou, develop_contract, consession_contract', 'default', 'setOnEmpty' => true, 'value' => null),
			array('application_form_id, project_name, company_name, mou, develop_contract, consession_contract, user_action_id, action_time', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'application_form_id' => Yii::t('app', 'Application Form'),
			'project_name' => Yii::t('app', 'Project Name'),
			'company_name' => Yii::t('app', 'Company Name'),
			'mou' => Yii::t('app', 'Mou'),
			'develop_contract' => Yii::t('app', 'Develop Contract'),
			'consession_contract' => Yii::t('app', 'Consession Contract'),
			'user_action_id' => Yii::t('app', 'User Action'),
			'action_time' => Yii::t('app', 'Action Time'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('application_form_id', $this->application_form_id);
		$criteria->compare('project_name', $this->project_name, true);
		$criteria->compare('company_name', $this->company_name, true);
		$criteria->compare('mou', $this->mou, true);
		$criteria->compare('develop_contract', $this->develop_contract, true);
		$criteria->compare('consession_contract', $this->consession_contract, true);
		$criteria->compare('user_action_id', $this->user_action_id);
		$criteria->compare('action_time', $this->action_time, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}