<?php

/**
 * This is the model base class for the table "appform_mining".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Mining".
 *
 * Columns in table "appform_mining" available as properties of the model,
 * followed by relations of table "appform_mining" available as properties of the model.
 *
 * @property integer $application_form_id
 * @property string $company_name
 * @property string $objective
 * @property integer $total_capital
 * @property integer $capital
 * @property integer $fixed_asset
 * @property integer $current_asset
 *
 * @property ApplicationForm $applicationForm
 * @property MiningProjectSite[] $miningProjectSites
 */
abstract class BaseMining extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'appform_mining';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Mining|Minings', $n);
	}

	public static function representingColumn() {
		return 'company_name';
	}

	public function rules() {
		return array(
			array('application_form_id, company_name, objective, total_capital, capital, fixed_asset, current_asset', 'required'),
			array('application_form_id, total_capital, capital, province_id, district_id, village_id, fixed_asset, current_asset', 'numerical', 'integerOnly'=>true),
			array('company_name, objective,address', 'length', 'max'=>255),
			array('application_form_id, company_name, objective, total_capital, capital, fixed_asset, current_asset', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'province' => array(self::BELONGS_TO, 'Province', 'province_id'),
			'district' => array(self::BELONGS_TO, 'District', 'district_id'),
			'village' => array(self::BELONGS_TO, 'Village', 'village_id'),
			'applicationForm' => array(self::BELONGS_TO, 'ApplicationForm', 'application_form_id'),
			'miningProjectSites' => array(self::HAS_MANY, 'MiningProjectSite', 'mining_application_form_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'application_form_id' => null,
			'company_name' => Yii::t('app', 'Company Name'),
			'objective' => Yii::t('app', 'Objective'),
			'total_capital' => Yii::t('app', 'Total Capital'),
			'capital' => Yii::t('app', 'Capital'),
			'fixed_asset' => Yii::t('app', 'Fixed Asset'),
			'current_asset' => Yii::t('app', 'Current Asset'),
			'applicationForm' => null,
			'miningProjectSites' => null,
			'province_id' => null,
			'district_id' => null,
			'village_id' => null,
			'address' => Yii::t('app', 'Address'),
			'province' => null,
			'district' => null,
			'village' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('application_form_id', $this->application_form_id);
		$criteria->compare('company_name', $this->company_name, true);
		$criteria->compare('objective', $this->objective, true);
		$criteria->compare('total_capital', $this->total_capital);
		$criteria->compare('capital', $this->capital);
		$criteria->compare('fixed_asset', $this->fixed_asset);
		$criteria->compare('current_asset', $this->current_asset);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}