<?php

/**
 * This is the model base class for the table "appform_application_email".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ApplicationEmail".
 *
 * Columns in table "appform_application_email" available as properties of the model,
 * followed by relations of table "appform_application_email" available as properties of the model.
 *
 * @property integer $id
 * @property integer $application_form_id
 * @property integer $application_step_id
 * @property string $email_date
 *
 * @property ApplicationForm $applicationForm
 * @property ApplicationStep $applicationStep
 */
abstract class BaseApplicationEmail extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'appform_application_email';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ApplicationEmail|ApplicationEmails', $n);
	}

	public static function representingColumn() {
		return 'email_date';
	}

	public function rules() {
		return array(
			array('application_form_id, application_step_id, email_date', 'required'),
			array('application_form_id, application_step_id', 'numerical', 'integerOnly'=>true),
			array('id, application_form_id, application_step_id, email_date', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'applicationForm' => array(self::BELONGS_TO, 'ApplicationForm', 'application_form_id'),
			'applicationStep' => array(self::BELONGS_TO, 'ApplicationStep', 'application_step_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'application_form_id' => null,
			'application_step_id' => null,
			'email_date' => Yii::t('app', 'Email Date'),
			'applicationForm' => null,
			'applicationStep' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('application_form_id', $this->application_form_id);
		$criteria->compare('application_step_id', $this->application_step_id);
		$criteria->compare('email_date', $this->email_date, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}