<?php

/**
 * This is the model base class for the table "appform_application_step".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ApplicationStep".
 *
 * Columns in table "appform_application_step" available as properties of the model,
 * followed by relations of table "appform_application_step" available as properties of the model.
 *
 * @property integer $id
 * @property string $step_description
 * @property integer $email_notify
 * @property string $email_content
 *
 * @property ApplicationEmail[] $applicationEmails
 * @property ApplicationForm[] $applicationForms
 */
abstract class BaseApplicationStep extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'appform_application_step';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ApplicationStep|ApplicationSteps', $n);
	}

	public static function representingColumn() {
		return 'step_description';
	}

	public function rules() {
		return array(
			array('step_description, email_notify', 'required'),
			array('email_notify', 'numerical', 'integerOnly'=>true),
			array('step_description', 'length', 'max'=>100),
			array('email_content', 'safe'),
			array('email_content', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, step_description, email_notify, email_content', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'applicationEmails' => array(self::HAS_MANY, 'ApplicationEmail', 'application_step_id'),
			'applicationForms' => array(self::HAS_MANY, 'ApplicationForm', 'application_step_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'step_description' => Yii::t('app', 'Step Description'),
			'email_notify' => Yii::t('app', 'Email Notify'),
			'email_content' => Yii::t('app', 'Email Content'),
			'applicationEmails' => null,
			'applicationForms' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('step_description', $this->step_description, true);
		$criteria->compare('email_notify', $this->email_notify);
		$criteria->compare('email_content', $this->email_content, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}