<?php

/**
 * This is the model base class for the table "appform_general_project_site".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "GeneralProjectSite".
 *
 * Columns in table "appform_general_project_site" available as properties of the model,
 * followed by relations of table "appform_general_project_site" available as properties of the model.
 *
 * @property integer $id
 * @property integer $general_application_form_id
 * @property integer $province_id
 * @property integer $district_id
 * @property integer $village_id
 *
 * @property District $district
 * @property General $generalApplicationForm
 * @property Province $province
 */
abstract class BaseGeneralProjectSite extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'appform_general_project_site';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'GeneralProjectSite|GeneralProjectSites', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('general_application_form_id, province_id, district_id', 'required'),
			array('general_application_form_id, province_id, district_id, village_id', 'numerical', 'integerOnly'=>true),
			array('village_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, general_application_form_id, province_id, district_id, village_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'district' => array(self::BELONGS_TO, 'District', 'district_id'),
			'generalApplicationForm' => array(self::BELONGS_TO, 'General', 'general_application_form_id'),
			'province' => array(self::BELONGS_TO, 'Province', 'province_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'general_application_form_id' => null,
			'province_id' => null,
			'district_id' => null,
			'village_id' => Yii::t('app', 'Village'),
			'district' => null,
			'generalApplicationForm' => null,
			'province' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('general_application_form_id', $this->general_application_form_id);
		$criteria->compare('province_id', $this->province_id);
		$criteria->compare('district_id', $this->district_id);
		$criteria->compare('village_id', $this->village_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}