<?php

/**
 * This is the model base class for the table "type_level".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TypeLevel".
 *
 * Columns in table "type_level" available as properties of the model,
 * followed by relations of table "type_level" available as properties of the model.
 *
 * @property integer $id
 * @property string $description
 * @property integer $parent_id
 *
 * @property DocumentType[] $documentTypes
 */
abstract class BaseTypeLevel extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'type_level';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TypeLevel|TypeLevels', $n);
	}

	public static function representingColumn() {
		return 'description';
	}

	public function rules() {
		return array(
			array('description', 'required'),
			array('parent_id', 'numerical', 'integerOnly'=>true),
			array('description', 'length', 'max'=>255),
			array('parent_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, description, parent_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'documentTypes' => array(self::HAS_MANY, 'DocumentType', 'type_level_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'description' => Yii::t('app', 'Description'),
			'parent_id' => Yii::t('app', 'Parent'),
			'documentTypes' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('parent_id', $this->parent_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}