<?php

/**
 * This is the model base class for the table "electric".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Electric".
 *
 * Columns in table "electric" available as properties of the model,
 * followed by relations of table "electric" available as properties of the model.
 *
 * @property integer $id
 * @property integer $inc_document_id
 * @property string $project_name
 * @property integer $province_id
 * @property integer $district_id
 * @property integer $village_id
 * @property string $company_name
 * @property string $mou
 * @property string $develop_contract
 * @property string $consession_contract
 *
 * @property District $district
 * @property IncDocument $incDocument
 * @property Province $province
 * @property Village $village
 * @property InvestElectrict $investElectrict
 */
abstract class BaseElectric extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'electric';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Electric|Electrics', $n);
	}

	public static function representingColumn() {
		return 'project_name';
	}

	public function rules() {
		return array(
			array('inc_document_id, project_name, province_id, district_id, village_id, company_name', 'required'),
			array('inc_document_id, province_id, district_id, village_id', 'numerical', 'integerOnly'=>true),
			array('project_name, company_name', 'length', 'max'=>255),
			array('mou, develop_contract, consession_contract', 'length', 'max'=>1),
			array('mou, develop_contract, consession_contract', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, inc_document_id, project_name, province_id, district_id, village_id, company_name, mou, develop_contract, consession_contract', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'district' => array(self::BELONGS_TO, 'District', 'district_id'),
			'incDocument' => array(self::BELONGS_TO, 'IncDocument', 'inc_document_id'),
			'province' => array(self::BELONGS_TO, 'Province', 'province_id'),
			'village' => array(self::BELONGS_TO, 'Village', 'village_id'),
			'investElectrict' => array(self::HAS_ONE, 'InvestElectrict', 'electric_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'inc_document_id' => null,
			'project_name' => Yii::t('app', 'Project Name'),
			'province_id' => null,
			'district_id' => null,
			'village_id' => null,
			'company_name' => Yii::t('app', 'Company Name'),
			'mou' => Yii::t('app', 'Mou'),
			'develop_contract' => Yii::t('app', 'Develop Contract'),
			'consession_contract' => Yii::t('app', 'Consession Contract'),
			'district' => null,
			'incDocument' => null,
			'province' => null,
			'village' => null,
			'investElectrict' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('inc_document_id', $this->inc_document_id);
		$criteria->compare('project_name', $this->project_name, true);
		$criteria->compare('province_id', $this->province_id);
		$criteria->compare('district_id', $this->district_id);
		$criteria->compare('village_id', $this->village_id);
		$criteria->compare('company_name', $this->company_name, true);
		$criteria->compare('mou', $this->mou, true);
		$criteria->compare('develop_contract', $this->develop_contract, true);
		$criteria->compare('consession_contract', $this->consession_contract, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}