<?php

/**
 * This is the model base class for the table "comment_to_user".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CommentToUser".
 *
 * Columns in table "comment_to_user" available as properties of the model,
 * followed by relations of table "comment_to_user" available as properties of the model.
 *
 * @property integer $id
 * @property integer $comment_id
 * @property integer $user_id
 *
 * @property Comment $comment
 * @property User $user
 */
abstract class BaseCommentToUser extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'comment_to_user';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CommentToUser|CommentToUsers', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('comment_id, user_id', 'required'),
			array('comment_id, user_id', 'numerical', 'integerOnly'=>true),
			array('id, comment_id, user_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'comment' => array(self::BELONGS_TO, 'Comment', 'comment_id'),
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'comment_id' => null,
			'user_id' => null,
			'comment' => null,
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('comment_id', $this->comment_id);
		$criteria->compare('user_id', $this->user_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}