<?php

/**
 * This is the model base class for the table "application_type".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ApplicationType".
 *
 * Columns in table "application_type" available as properties of the model,
 * followed by relations of table "application_type" available as properties of the model.
 *
 * @property integer $id
 * @property string $description
 *
 * @property IncDocument[] $incDocuments
 */
abstract class BaseApplicationType extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'application_type';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ApplicationType|ApplicationTypes', $n);
	}

	public static function representingColumn() {
		return 'description';
	}

	public function rules() {
		return array(
			array('description', 'required'),
			array('description', 'length', 'max'=>255),
			array('id, description', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'incDocuments' => array(self::HAS_MANY, 'IncDocument', 'application_type_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'description' => Yii::t('app', 'Description'),
			'incDocuments' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('description', $this->description, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}