<?php

/**
 * This is the model base class for the table "rep_office".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "RepOffice".
 *
 * Columns in table "rep_office" available as properties of the model,
 * followed by relations of table "rep_office" available as properties of the model.
 *
 * @property integer $id
 * @property integer $inc_document_id
 * @property string $first_name
 * @property string $last_name
 * @property string $birth_date
 * @property string $nationality
 * @property string $parent_company
 * @property string $register_place
 * @property string $business
 * @property string $objective
 * @property string $house_no
 * @property integer $province_id
 * @property integer $district_id
 * @property integer $village_id
 * @property integer $capital
 * @property integer $fixed_asset
 * @property integer $cash
 *
 * @property District $district
 * @property Province $province
 * @property IncDocument $incDocument
 * @property Village $village
 */
abstract class BaseRepOffice extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'rep_office';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'RepOffice|RepOffices', $n);
	}

	public static function representingColumn() {
		return 'first_name';
	}

	public function rules() {
		return array(
			array('inc_document_id, first_name, last_name, birth_date, nationality, parent_company, register_place, business, objective, province_id, district_id, village_id, capital, fixed_asset, cash', 'required'),
			array('inc_document_id, province_id, district_id, village_id, capital, fixed_asset, cash', 'numerical', 'integerOnly'=>true),
			array('first_name, last_name, nationality, parent_company, register_place', 'length', 'max'=>255),
			array('house_no', 'length', 'max'=>45),
			array('house_no', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, inc_document_id, first_name, last_name, birth_date, nationality, parent_company, register_place, business, objective, house_no, province_id, district_id, village_id, capital, fixed_asset, cash', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'district' => array(self::BELONGS_TO, 'District', 'district_id'),
			'province' => array(self::BELONGS_TO, 'Province', 'province_id'),
			'incDocument' => array(self::BELONGS_TO, 'IncDocument', 'inc_document_id'),
			'village' => array(self::BELONGS_TO, 'Village', 'village_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'inc_document_id' => null,
			'first_name' => Yii::t('app', 'First Name'),
			'last_name' => Yii::t('app', 'Last Name'),
			'birth_date' => Yii::t('app', 'Birth Date'),
			'nationality' => Yii::t('app', 'Nationality'),
			'parent_company' => Yii::t('app', 'Parent Company'),
			'register_place' => Yii::t('app', 'Register Place'),
			'business' => Yii::t('app', 'Business'),
			'objective' => Yii::t('app', 'Objective'),
			'house_no' => Yii::t('app', 'House No'),
			'province_id' => null,
			'district_id' => null,
			'village_id' => null,
			'capital' => Yii::t('app', 'Capital'),
			'fixed_asset' => Yii::t('app', 'Fixed Asset'),
			'cash' => Yii::t('app', 'Cash'),
			'district' => null,
			'province' => null,
			'incDocument' => null,
			'village' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('inc_document_id', $this->inc_document_id);
		$criteria->compare('first_name', $this->first_name, true);
		$criteria->compare('last_name', $this->last_name, true);
		$criteria->compare('birth_date', $this->birth_date, true);
		$criteria->compare('nationality', $this->nationality, true);
		$criteria->compare('parent_company', $this->parent_company, true);
		$criteria->compare('register_place', $this->register_place, true);
		$criteria->compare('business', $this->business, true);
		$criteria->compare('objective', $this->objective, true);
		$criteria->compare('house_no', $this->house_no, true);
		$criteria->compare('province_id', $this->province_id);
		$criteria->compare('district_id', $this->district_id);
		$criteria->compare('village_id', $this->village_id);
		$criteria->compare('capital', $this->capital);
		$criteria->compare('fixed_asset', $this->fixed_asset);
		$criteria->compare('cash', $this->cash);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}