<?php

/**
 * This is the model base class for the table "invest_general".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "InvestGeneral".
 *
 * Columns in table "invest_general" available as properties of the model,
 * followed by relations of table "invest_general" available as properties of the model.
 *
 * @property integer $general_id
 * @property integer $invest_company_id
 *
 * @property General $general
 * @property InvestCompany $investCompany
 */
abstract class BaseInvestGeneral extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'invest_general';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'InvestGeneral|InvestGenerals', $n);
	}

	public static function representingColumn() {
		return 'general_id';
	}

	public function rules() {
		return array(
			array('general_id, invest_company_id', 'required'),
			array('general_id, invest_company_id', 'numerical', 'integerOnly'=>true),
			array('general_id, invest_company_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'general' => array(self::BELONGS_TO, 'General', 'general_id'),
			'investCompany' => array(self::BELONGS_TO, 'InvestCompany', 'invest_company_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'general_id' => null,
			'invest_company_id' => null,
			'general' => null,
			'investCompany' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('general_id', $this->general_id);
		$criteria->compare('invest_company_id', $this->invest_company_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}