<?php

/**
 * This is the model base class for the table "district".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "District".
 *
 * Columns in table "district" available as properties of the model,
 * followed by relations of table "district" available as properties of the model.
 *
 * @property integer $id
 * @property integer $province_id
 * @property string $district_name
 *
 * @property Province $province
 * @property Electric[] $electrics
 * @property General[] $generals
 * @property Mining[] $minings
 * @property RepOffice[] $repOffices
 * @property Village[] $villages
 */
abstract class BaseDistrict extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'district';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'District|Districts', $n);
	}

	public static function representingColumn() {
		return 'district_name';
	}

	public function rules() {
		return array(
			array('province_id, district_name', 'required'),
			array('province_id', 'numerical', 'integerOnly'=>true),
			array('district_name', 'length', 'max'=>255),
			array('id, province_id, district_name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'province' => array(self::BELONGS_TO, 'Province', 'province_id'),
			'electrics' => array(self::HAS_MANY, 'Electric', 'district_id'),
			'generals' => array(self::HAS_MANY, 'General', 'district_id'),
			'minings' => array(self::HAS_MANY, 'Mining', 'district_id'),
			'repOffices' => array(self::HAS_MANY, 'RepOffice', 'district_id'),
			'villages' => array(self::HAS_MANY, 'Village', 'district_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'province_id' => null,
			'district_name' => Yii::t('app', 'District Name'),
			'province' => null,
			'electrics' => null,
			'generals' => null,
			'minings' => null,
			'repOffices' => null,
			'villages' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('province_id', $this->province_id);
		$criteria->compare('district_name', $this->district_name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}