<?php

/**
 * This is the model base class for the table "from_to".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "FromTo".
 *
 * Columns in table "from_to" available as properties of the model,
 * followed by relations of table "from_to" available as properties of the model.
 *
 * @property integer $id
 * @property integer $from_organization_id
 * @property integer $to_organization_id
 *
 * @property Organization $fromOrganization
 * @property Organization $toOrganization
 */
abstract class BaseFromTo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'from_to';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'FromTo|FromTos', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('from_organization_id, to_organization_id', 'required'),
			array('from_organization_id, to_organization_id', 'numerical', 'integerOnly'=>true),
			array('id, from_organization_id, to_organization_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'fromOrganization' => array(self::BELONGS_TO, 'Organization', 'from_organization_id'),
			'toOrganization' => array(self::BELONGS_TO, 'Organization', 'to_organization_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'from_organization_id' => null,
			'to_organization_id' => null,
			'fromOrganization' => null,
			'toOrganization' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('from_organization_id', $this->from_organization_id);
		$criteria->compare('to_organization_id', $this->to_organization_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}