<?php

/**
 * This is the model base class for the table "attach_file".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AttachFile".
 *
 * Columns in table "attach_file" available as properties of the model,
 * followed by relations of table "attach_file" available as properties of the model.
 *
 * @property integer $id
 * @property integer $document_id
 * @property string $file_name
 * @property string $title
 *
 * @property Document $document
 */
abstract class BaseAttachFile extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'attach_file';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AttachFile|AttachFiles', $n);
	}

	public static function representingColumn() {
		return 'file_name';
	}

	public function rules() {
		return array(
			array('document_id, file_name,title', 'required'),
			array('document_id', 'numerical', 'integerOnly'=>true),
			//array('file_name', 'length', 'max'=>60),
			array('file_name', 'file', 'types'=>'jpg,pdf,doc,docx','maxSize'=>1024*1024*5,'on'=>'insert'),
			array('title', 'length', 'max'=>255),
			array('id, document_id, file_name, title', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'document' => array(self::BELONGS_TO, 'Document', 'document_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'document_id' => null,
			'file_name' => Yii::t('app', 'File Name'),
			'title' => Yii::t('app', 'Title name'),
			'document' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('document_id', $this->document_id);
		$criteria->compare('file_name', $this->file_name, true);
		$criteria->compare('title', $this->title, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}