<?php

/**
 * This is the model base class for the table "region".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Region".
 *
 * Columns in table "region" available as properties of the model,
 * followed by relations of table "region" available as properties of the model.
 *
 * @property integer $id
 * @property string $region_name
 * @property string $region_code
 *
 * @property Organization[] $organizations
 */
abstract class BaseRegion extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'region';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Region|Regions', $n);
	}

	public static function representingColumn() {
		return 'region_name';
	}

	public function rules() {
		return array(
			array('region_name, region_code', 'required'),
			array('region_name', 'length', 'max'=>255),
			array('region_code', 'length', 'max'=>50),
			array('id, region_name, region_code', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'organizations' => array(self::HAS_MANY, 'Organization', 'region_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'region_name' => Yii::t('app', 'Region Name'),
			'region_code' => Yii::t('app', 'Region Code'),
			'organizations' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('region_name', $this->region_name, true);
		$criteria->compare('region_code', $this->region_code, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}