<?php

/**
 * This is the model base class for the table "inc_document_history".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "IncDocumentHistory".
 *
 * Columns in table "inc_document_history" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $document_id
 * @property string $inc_document_no
 * @property string $document_date
 * @property string $document_title
 * @property integer $related_document_id
 * @property integer $from_organization_id
 * @property integer $to_organization_id
 * @property integer $document_status_id
 * @property integer $document_type_id
 * @property integer $application_type_id
 * @property string $is_application
 * @property string $sender
 * @property string $sender_ref
 * @property string $created
 * @property integer $created_by
 * @property string $last_modified
 * @property integer $last_modified_id
 * @property integer $user_action_id
 * @property string $action_time
 *
 */
abstract class BaseIncDocumentHistory extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'inc_document_history';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'IncDocumentHistory|IncDocumentHistories', $n);
	}

	public static function representingColumn() {
		return 'inc_document_no';
	}

	public function rules() {
		return array(
			array('document_id, inc_document_no, document_date, document_title, from_organization_id, to_organization_id, document_status_id, document_type_id, is_application, created, created_by, last_modified, last_modified_id, user_action_id, action_time', 'required'),
			array('document_id, related_document_id, from_organization_id, to_organization_id, document_status_id, document_type_id, application_type_id, created_by, last_modified_id, user_action_id', 'numerical', 'integerOnly'=>true),
			array('inc_document_no', 'length', 'max'=>17),
			array('is_application', 'length', 'max'=>4),
			array('sender', 'length', 'max'=>255),
			array('sender_ref', 'length', 'max'=>60),
			array('related_document_id, application_type_id, sender, sender_ref', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, document_id, inc_document_no, document_date, document_title, related_document_id, from_organization_id, to_organization_id, document_status_id, document_type_id, application_type_id, is_application, sender, sender_ref, created, created_by, last_modified, last_modified_id, user_action_id, action_time', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'document_id' => Yii::t('app', 'Document'),
			'inc_document_no' => Yii::t('app', 'Inc Document No'),
			'document_date' => Yii::t('app', 'Document Date'),
			'document_title' => Yii::t('app', 'Document Title'),
			'related_document_id' => Yii::t('app', 'Related Document'),
			'from_organization_id' => Yii::t('app', 'From Organization'),
			'to_organization_id' => Yii::t('app', 'To Organization'),
			'document_status_id' => Yii::t('app', 'Document Status'),
			'document_type_id' => Yii::t('app', 'Document Type'),
			'application_type_id' => Yii::t('app', 'Application Type'),
			'is_application' => Yii::t('app', 'Is Application'),
			'sender' => Yii::t('app', 'Sender'),
			'sender_ref' => Yii::t('app', 'Sender Ref'),
			'created' => Yii::t('app', 'Created'),
			'created_by' => Yii::t('app', 'Created By'),
			'last_modified' => Yii::t('app', 'Last Modified'),
			'last_modified_id' => Yii::t('app', 'Last Modified'),
			'user_action_id' => Yii::t('app', 'User Action'),
			'action_time' => Yii::t('app', 'Action Time'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('document_id', $this->document_id);
		$criteria->compare('inc_document_no', $this->inc_document_no, true);
		$criteria->compare('document_date', $this->document_date, true);
		$criteria->compare('document_title', $this->document_title, true);
		$criteria->compare('related_document_id', $this->related_document_id);
		$criteria->compare('from_organization_id', $this->from_organization_id);
		$criteria->compare('to_organization_id', $this->to_organization_id);
		$criteria->compare('document_status_id', $this->document_status_id);
		$criteria->compare('document_type_id', $this->document_type_id);
		$criteria->compare('application_type_id', $this->application_type_id);
		$criteria->compare('is_application', $this->is_application, true);
		$criteria->compare('sender', $this->sender, true);
		$criteria->compare('sender_ref', $this->sender_ref, true);
		$criteria->compare('created', $this->created, true);
		$criteria->compare('created_by', $this->created_by);
		$criteria->compare('last_modified', $this->last_modified, true);
		$criteria->compare('last_modified_id', $this->last_modified_id);
		$criteria->compare('user_action_id', $this->user_action_id);
		$criteria->compare('action_time', $this->action_time, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}