<?php

/**
 * This is the model base class for the table "_sequence".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Sequence".
 *
 * Columns in table "_sequence" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $seq_name
 * @property string $seq_type
 * @property string $seq_group
 * @property string $seq_year
 * @property string $seq_value
 *
 */
abstract class BaseSequence extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '_sequence';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Sequence|Sequences', $n);
	}

	public static function representingColumn() {
		return 'seq_year';
	}

	public function rules() {
		return array(
			array('seq_name, seq_type, seq_group, seq_year, seq_value', 'required'),
			array('seq_name', 'length', 'max'=>50),
			array('seq_type', 'length', 'max'=>1),
			array('seq_group', 'length', 'max'=>5),
			array('seq_year', 'length', 'max'=>2),
			array('seq_value', 'length', 'max'=>10),
			array('seq_name, seq_type, seq_group, seq_year, seq_value', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'seq_name' => Yii::t('app', 'Seq Name'),
			'seq_type' => Yii::t('app', 'Seq Type'),
			'seq_group' => Yii::t('app', 'Seq Group'),
			'seq_year' => Yii::t('app', 'Seq Year'),
			'seq_value' => Yii::t('app', 'Seq Value'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('seq_name', $this->seq_name, true);
		$criteria->compare('seq_type', $this->seq_type, true);
		$criteria->compare('seq_group', $this->seq_group, true);
		$criteria->compare('seq_year', $this->seq_year, true);
		$criteria->compare('seq_value', $this->seq_value, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}