<?php

/**
 * This is the model base class for the table "mining_history".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MiningHistory".
 *
 * Columns in table "mining_history" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $inc_document_id
 * @property string $company_name
 * @property string $objective
 * @property integer $province_id
 * @property integer $district_id
 * @property integer $village_id
 * @property integer $total_capital
 * @property integer $capital
 * @property integer $fixed_asset
 * @property integer $current_asset
 * @property integer $user_action_id
 * @property string $action_time
 *
 */
abstract class BaseMiningHistory extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mining_history';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MiningHistory|MiningHistories', $n);
	}

	public static function representingColumn() {
		return 'company_name';
	}

	public function rules() {
		return array(
			array('id, inc_document_id, company_name, objective, province_id, district_id, village_id, total_capital, capital, fixed_asset, current_asset, user_action_id, action_time', 'required'),
			array('id, inc_document_id, province_id, district_id, village_id, total_capital, capital, fixed_asset, current_asset, user_action_id', 'numerical', 'integerOnly'=>true),
			array('company_name, objective', 'length', 'max'=>255),
			array('id, inc_document_id, company_name, objective, province_id, district_id, village_id, total_capital, capital, fixed_asset, current_asset, user_action_id, action_time', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'inc_document_id' => Yii::t('app', 'Inc Document'),
			'company_name' => Yii::t('app', 'Company Name'),
			'objective' => Yii::t('app', 'Objective'),
			'province_id' => Yii::t('app', 'Province'),
			'district_id' => Yii::t('app', 'District'),
			'village_id' => Yii::t('app', 'Village'),
			'total_capital' => Yii::t('app', 'Total Capital'),
			'capital' => Yii::t('app', 'Capital'),
			'fixed_asset' => Yii::t('app', 'Fixed Asset'),
			'current_asset' => Yii::t('app', 'Current Asset'),
			'user_action_id' => Yii::t('app', 'User Action'),
			'action_time' => Yii::t('app', 'Action Time'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('inc_document_id', $this->inc_document_id);
		$criteria->compare('company_name', $this->company_name, true);
		$criteria->compare('objective', $this->objective, true);
		$criteria->compare('province_id', $this->province_id);
		$criteria->compare('district_id', $this->district_id);
		$criteria->compare('village_id', $this->village_id);
		$criteria->compare('total_capital', $this->total_capital);
		$criteria->compare('capital', $this->capital);
		$criteria->compare('fixed_asset', $this->fixed_asset);
		$criteria->compare('current_asset', $this->current_asset);
		$criteria->compare('user_action_id', $this->user_action_id);
		$criteria->compare('action_time', $this->action_time, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}