<?php

/**
 * This is the model base class for the table "invest_electrict".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "InvestElectrict".
 *
 * Columns in table "invest_electrict" available as properties of the model,
 * followed by relations of table "invest_electrict" available as properties of the model.
 *
 * @property integer $electric_id
 * @property integer $invest_company_id
 *
 * @property Electric $electric
 * @property InvestCompany $investCompany
 */
abstract class BaseInvestElectrict extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'invest_electrict';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'InvestElectrict|InvestElectricts', $n);
	}

	public static function representingColumn() {
		return 'electric_id';
	}

	public function rules() {
		return array(
			array('electric_id, invest_company_id', 'required'),
			array('electric_id, invest_company_id', 'numerical', 'integerOnly'=>true),
			array('electric_id, invest_company_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'electric' => array(self::BELONGS_TO, 'Electric', 'electric_id'),
			'investCompany' => array(self::BELONGS_TO, 'InvestCompany', 'invest_company_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'electric_id' => null,
			'invest_company_id' => null,
			'electric' => null,
			'investCompany' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('electric_id', $this->electric_id);
		$criteria->compare('invest_company_id', $this->invest_company_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}